# Run tests
# Run a rehearsal of the publishing process to TestPyPI

name: Test published package on TestPyPi

on:
  push:
    tags: ['v*']

env:
  SECRET_GARDEN_LOCAL: 'false'

jobs:
    
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:

    - uses: actions/checkout@v4.1.1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.2.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry config virtualenvs.create false
        python -m poetry install --no-dev
        python -m poetry add pytest 
        python -m poetry config repositories.testpypi https://test.pypi.org/simple
        python -m poetry add secret-garden --source testpypi

    - name: Test with pytest
      run: |
        python -m pytest -s
