# Run tests
# Run a rehearsal of the publishing process to TestPyPI

name: Publish to PyPI

on:
  workflow_run:
    workflows: ["Test published package on TestPyPi"]
    types:
      - completed

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4.1.1

    - name: Set up Python
      uses: actions/setup-python@v4.2.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      continue-on-error: false
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Setup pypi in poetry
      continue-on-error: false
      run: | 
        python -m poetry config repositories.pypi 'https://upload.pypi.org/legacy/'
        python -m poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

    - name: Build and publish
      run: |
        python -m poetry build
        python -m poetry publish -r pypi -u __token__
